[package]
name = "viz-echo"
version = "0.1.0"
edition = "2021"

[dependencies]
viz = "0.8.0"
socketioxide = { path = "../../socketioxide" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true
tracing.workspace = true
serde_json.workspace = true

[[bin]]
name = "viz-echo"
path = "viz_echo.rs"
