[workspace]
members = ["engineioxide", "socketioxide", "e2e/*", "examples/*"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.27"
tokio = "1.35.0"
tokio-tungstenite = "0.20.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tower = { version = "0.4.13", default-features = false }
http = "0.2.11"
http-body = "0.4.5"
thiserror = "1.0.40"
tracing = "0.1.37"
itoa = "1.0.10"

# Hyper v0.1
http-body-v1 = { package = "http-body", version = "1.0.0-rc.2" }
hyper-v1 = { package = "hyper", version = "1.0.0-rc.4", features = [
    "server",
    "http1",
    "http2",
] }

# Dev deps
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
    "client",
] }
axum = "0.6.20"
warp = "0.3.6"
salvo = { version = "0.58.5", features = ["tower-compat"] }

[workspace.package]
version = "0.7.3"
edition = "2021"
rust-version = "1.67.0"
authors = ["Théodore Prévot <"]
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["socketio", "tower", "axum", "hyper", "websocket"]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming::websocket",
]
license = "MIT"
