[workspace.package]
version = "0.11.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["Théodore Prévot <"]
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["socketio", "tower", "axum", "hyper", "websocket"]
categories = [
	"asynchronous",
	"network-programming",
	"web-programming::websocket",
]
license = "MIT"

[workspace]
members = ["engineioxide", "socketioxide", "e2e/*", "examples/*"]
default-members = ["engineioxide", "socketioxide"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.27"
tokio = "1.35.0"
tokio-tungstenite = "0.21.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tower = { version = "0.4.13", default-features = false }
http = "1.0.0"
http-body = "1.0.0"
http-body-util = { version = "0.1.0" }
thiserror = "1.0.40"
tracing = "0.1.37"
itoa = "1.0.10"
hyper-util.version = "0.1.1"
hyper = { version = "1.0.1", features = ["http1", "http2", "server"] }
pin-project-lite = "0.2.13"

# Dev deps
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
axum = "0.7.2"
salvo = { version = "0.66.0", features = ["tower-compat"] }
rust_socketio = { version = "0.4.2", features = ["async"] }
