[package]
name = "loco_chat_rooms"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"    # required by loco

[dependencies]

loco-rs = { version = "0.2.3", default-features = false, features = [
    "cli",
    "channels",
] }
eyre = "0.6.11"
async-trait = "0.1.74"
chrono = { version = "0.4", features = ["serde"] }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[[bin]]
name = "loco_chat_rooms-cli"
path = "src/bin/main.rs"
required-features = []
