[package]
name = "hyper-v1-echo"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketioxide = { path = "../../socketioxide", features = [
    "hyper-v1",
    "tracing",
] }
hyper-v1 = { workspace = true, features = ["server", "http1", "http2"] }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git", version = "0" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true
tracing.workspace = true
serde_json.workspace = true

[[bin]]
name = "hyper-v1-echo"
path = "hyper_v1_echo.rs"
