name: SocketIO CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: cargo fmt --all -- --check
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v3
        with:
          repository: socketio/socket.io-protocol
          path: socket.io-protocol
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps & run tests 
        run: |
          cd socket.io-protocol/test-suite && npm install && cd ../..
          cargo build --bin socketioxide-e2e --release
          cargo run --bin socketioxide-e2e --release > server.txt & npm --prefix socket.io-protocol/test-suite test > client.txt
      - name: Server output
        if: always()
        run: cat server.txt
      - name: Client output
        if: always()
        run:  cat client.txt